### ISSUE TITLE
Link to Red Hat site must start with HTTPS://

### ISSUE THREAD

**Issue by lemenkov** [RedHatOfficial/RedHatOfficial.github.io#102]
![Screenshot](http://www.imagehosting.cz/images/screenvqv.png)

**Comment by castastrophe** [comment]
@bproffitt Hmm, I don't seem able to change this information on the Organization main page.  Are you able to make this update?

**Comment by bproffitt** [comment]
@castastrophe Let me try

**Comment by bproffitt** [comment]
@castastrophe Got it. Closing. Thanks, @lemenkov !
