### ISSUE TITLE
Content Not Updating

### ISSUE THREAD

**Issue by bproffitt** [RedHatOfficial/RedHatOfficial.github.io#106]
Merging is going well, but the site itself is still not updated. Can we add an automated process to the CI flow that will auto-build the app after each checked update?

**Comment by castastrophe** [comment]
I'd love that but that's not my skillset so we'll need to recruit a developer with that expertise.

**Comment by bproffitt** [comment]
Okay, but can you update it now? I have caught up with the PRs and I'd like to see them go live.

**Comment by bproffitt** [comment]
Fixed with #138! Closing.
