### ISSUE TITLE
Some changes have been rolled back

### ISSUE THREAD

**Issue by theute** [RedHatOfficial/RedHatOfficial.github.io#122]
I added Kiali here:
https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/6

And it's been removed by this commit later:
https://github.com/RedHatOfficial/RedHatOfficial.github.io/commit/010e7a1a25897dba5e0c9036c99d7c01885f8240

Other projects might have been affected

**Comment by bproffitt** [comment]
Yeah, I actually noticed that, because Kiali was one of the first to be added, and I was using it as a marker to tell me if the page had reloaded. It may have gotten stomped on in one of the early commit conflicts. My apologies, I will fix this now.

**Comment by bproffitt** [comment]
Closed, completed in #126

**Comment by theute** [comment]
Thanks !
