### ISSUE TITLE
Remove "Obsidian Toaster" as a public-facing entity

### ISSUE THREAD

**Issue by ALRubinger** [RedHatOfficial/RedHatOfficial.github.io#136]
Obsidian Toaster is an internal Middleware initiative with several outputs and communities.  This issue to track PRs for removing "Obsidian Toaster" from the project list in favor of the upstream projects it encompasses.

The RHOAR and Middleware Developer Experience teams will be attaching PRs linked here; no action needed by the RedHatOfficial.github.io maintainers at the moment; thanks!

**Comment by gastaldi** [comment]
I believe the Red Hat Kontinuity org needs to be removed as well?

**Comment by ALRubinger** [comment]
@gastaldi Absolutely.

**Comment by bproffitt** [comment]
Okay, all, will merge the PRs as they come in.
