### ISSUE TITLE
Mention Drools, OptaPlanner and jBPM (not just KIE)

### ISSUE THREAD

**Issue by ge0ffrey** [RedHatOfficial/RedHatOfficial.github.io#145]
Red Hat sponsors drools.org, optaplanner.org and jbpm.org.
On GitHub, they are all in the GitHub organization kiegroup, which probably explains why they aren't mentioned individually, but they should.

- Drools - https://www.drools.org/ - https://github.com/kiegroup/drools
- OptaPlanner - https://www.optaplanner.org/ - https://github.com/kiegroup/optaplanner
- jBPM - https://www.jbpm.org/ - https://github.com/kiegroup/jbpm

**Comment by bproffitt** [comment]
Yeah, I am unsure how to handle this. All the public-facing content makes a strong point to refer to KIE, which is why it was consolidated here. Plus, for now we're trying to only list top-level projects, so another reason to highlight KIE.

**Comment by ge0ffrey** [comment]
FWIW, I've updated ticket with suggested name, website url and repo url's.

On Red Hat developer's projects page, they are mentioned separately.
  https://developers.redhat.com/projects/#!

**Comment by tarilabs** [comment]
Hi @bproffitt 

As @ge0ffrey highlighted Drools, OptaPlanner and jBPM are separate projects:

> On Red Hat developer's projects page, they are mentioned separately. https://developers.redhat.com/projects/

I believe on this landing page instead we are giving semantics to a GitHub organization for a project/subproject structure, which doesn't necessarily apply to all projects and especially to Kie as it's only used for the pragmatical organisation of tying the projects together (as they have affinity, but indeed separate projects).

Based on the above, I understand there will be a research to better accomodate other types of GitHub setups (https://github.com/RedHatOfficial/RedHatOfficial.github.io/issues/150) but meanwhile for all the reasons explained for Drools, OptaPlanner and jBPM can we kindly merge https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/149 please?

Thank you in advance for your feedback
