### ISSUE TITLE
Add OpenShift Origin to  featured projects section

### ISSUE THREAD

**Issue by dmueller2001** [RedHatOfficial/RedHatOfficial.github.io#152]
Please add OpenShift to the the Featured Projects section for Containers. 

https://github.com/openshift

logo: 
![openshift-logotype svg](https://user-images.githubusercontent.com/4029488/38166175-44508480-34d4-11e8-8e29-dc3c4998a138.png)

@bproffitt

**Comment by bproffitt** [comment]
Completed with #155. Closing.
