### ISSUE TITLE
Add Eclipse Vert.x to the Featured section

### ISSUE THREAD

**Issue by rdruss** [RedHatOfficial/RedHatOfficial.github.io#154]
I would like to request that Eclipse Vert.x be added to the Featured section of 
 https://redhatofficial.github.io

A version of the logo can be found here: https://vertx.io/assets/logo-sm.png along with a brief we description, "Eclipse Vert.x is a tool-kit for building reactive applications on the JVM."

Let me know if you need anything else from me.

**Comment by bproffitt** [comment]
Completed with #155. Closing.
