### ISSUE TITLE
Please add Charlotte to the list

### ISSUE THREAD

**Issue by rmonk** [RedHatOfficial/RedHatOfficial.github.io#159]
Here's the details:

{
  "projectName": "Charlotte",
  "projectDescription": "A Snort unified file to database processor",
  "projectRepository": "https://github.com/redhat-infosec/charlotte",
  "projectWebsite": "https://github.com/redhat-infosec/charlotte",
  "category": "Operations"
}

Thanks!

**Comment by bproffitt** [comment]
Closed per #161
