### ISSUE TITLE
Add a "projectStatus" property to projects

### ISSUE THREAD

**Issue by jpkrohling** [RedHatOfficial/RedHatOfficial.github.io#178]
Quite a few projects listed on the file `projects.json` are archived (halted, sunset, terminated and other variations). One such example close to me is GateIn: the last commit on a module I maintain is more than one year old. The last commit on the "core" module is close to two years ago. Other projects I randomly checked are 6 years without a commit (BoxGrinder, for instance).

In benefit of active projects, it would probably be useful to *not* list GateIn on the main list. If desired, it could be shown in a separate section, or if the user actively checks a box saying "display archived projects".

**Comment by Shubhrmcf07** [comment]
Can you spare some more details? I am interested to take this up

**Comment by bproffitt** [comment]
Time to do an audit!
