### ISSUE TITLE
lots of node security issues here

### ISSUE THREAD

**Issue by spotrh** [RedHatOfficial/RedHatOfficial.github.io#188]
npm audit shows a lot of vulnerable components...

**Comment by spotrh** [comment]
[audit.log](https://github.com/RedHatOfficial/RedHatOfficial.github.io/files/2483918/audit.log)

**Comment by castastrophe** [comment]
Would definitely accept PRs with updates

**Comment by castastrophe** [comment]
We have dependabot set up so I'm going to close this for now.  If there are specific issues we can resolve, please don't hesitate to reach out!
