### ISSUE TITLE
Sort alphabetically entries in project.json file

### ISSUE THREAD

**Issue by apupier** [RedHatOfficial/RedHatOfficial.github.io#19]
it will be easier when having the file opened to check for projects if they exist or not

**Comment by castastrophe** [comment]
It's loosely sorted alphabetically but since it is manually updated, it's not that easy to keep it perfect.  The listing should be alphabetical though on the front-end and you're welcome to start there.  We're also asking new entries be added as close to alphabetical as possible.

**Comment by greg-hellings** [comment]
Once the PRs settle down it should be easy to hack a script that will truly alphabetize it once, then you can enforce it permanently after that. Or break out each entry into its own file, as a later PR suggests would be a much easier maintenance headache.

**Comment by iranzo** [comment]
~~~py
#!/usr/bin/env python
import json
data=json.loads(open('projects.json','r').read())
def getKey(item):
    return item['projectName']

newdata=sorted(data,key=getKey)
filename='sorted.json'
with open(filename, 'w') as fd:
    json.dump(newdata, fd, indent=2)

~~~

**Comment by iranzo** [comment]
Covered in https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/100

**Comment by castastrophe** [comment]
Thanks!  I added a question in the PR.

**Comment by iranzo** [comment]
I would do a second update if it's not sorted to do that automatically and
save time of submitter

**Comment by Fryguy** [comment]
> I would do a second update if it's not sorted to do that automatically and save time of submitter

My only reason against that idea is commit-history churn...It will read like "add-a-project, move-a-project, add-a-project, move-a-project"

**Comment by iranzo** [comment]
We'll that's not the best approach, but asking users to keep order in a big file that can be editted in parallel from several other users isn't either... probably file-per-project would have been better and will avoid conficlts and sorting will come from the static site generator (order once per web upload)

**Comment by bproffitt** [comment]
If this is something we can add to the CI check, then I am for it. But I would put this as a low-priority need, since the maintainers of this site should be able to alphabetize during the quarterly audits.

**Comment by bproffitt** [comment]
#70 is a better approach and would solve this issue. Closing in deference to that approach.
