### ISSUE TITLE
Add Twitter column to page listing

### ISSUE THREAD

**Issue by jkbrock** [RedHatOfficial/RedHatOfficial.github.io#229]
Many projects have active twitter accounts that are updated more frequently than their websites and blogs. I would propose to add a column for a link to their feed.

**Comment by castastrophe** [comment]
@jkbrock That sounds like a great idea!  I would definitely accept any pull requests that make that update.

**Comment by pcast11** [comment]
Hi! I'm interested in working on this issue but I seem to be having some trouble setting up my dev environment to run the page locally. Would it be possible to get the information on how to do that?

**Comment by castastrophe** [comment]
@pcast11 Thank you so much for your offer to help!  I will add an issue to go in and add instructions to pull down the project and build.  In the meantime, run `npm install && npm run start`.

**Comment by pcast11** [comment]
#234 I added a possible solution here in this pull request.
