### ISSUE TITLE
Notifications of Pull Requests

### ISSUE THREAD

**Issue by bproffitt** [RedHatOfficial/RedHatOfficial.github.io#230]
I was not getting notifications of any pull requests since November 2019 (and nothing in Spam). I have added my email address to the Notifications settings for this repo now. Is that all I need to do? Sorry for not seeing any of the pending PRs; I never knew they were there until @castastrophe merged them.

**Comment by castastrophe** [comment]
@bproffitt Do you still need this issue open?
