### ISSUE TITLE
Add documentation for setting up repo for development

### ISSUE THREAD

**Issue by castastrophe** [RedHatOfficial/RedHatOfficial.github.io#233]
It was brought to our attention that this project doesn't have a file with instructions on setting up the project for development.

**Comment by jugalj05hi** [comment]
Hello there, this would be my first meaningful contribution to the Open Source. Is this something a beginner can take up? Thank you.

**Comment by castastrophe** [comment]
Documentation is a great way to get your feet wet with open source. I'm not sure if this is the best place to jump in though. There's nothing to get you started so you'd have to parse the package.json and intuit which scripts to run.

**Comment by DARK-art108** [comment]
Can I work on this issue?

**Comment by castastrophe** [comment]
@DARK-art108 You're welcome to pick this up if you like.  We're hoping to add the following items:

- Add a Quick start to the README, [example here](https://github.com/patternfly/patternfly-elements#quick-start)
- Contribution guidelines, [example here](https://github.com/lerna/lerna/blob/master/CONTRIBUTING.md)

**Comment by castastrophe** [comment]
The package.json contains the definition of the scripts available.  The project was set up using webpack as the compiler.

**Comment by DARK-art108** [comment]
I have added a quick start guide for setup the repo in development mode please review it.

**Comment by castastrophe** [comment]
@DARK-art108 Are you able to open a pull request?

**Comment by DARK-art108** [comment]
Yes,I have opened a pull request recently.

**Comment by DARK-art108** [comment]
Pls, review the pull request #238 @castastrophe

**Comment by DARK-art108** [comment]
Pls, review the pull request #239 @castastrophe

**Comment by DARK-art108** [comment]
Pls, review the pull request #239 @castastrophe
