### ISSUE TITLE
Apache Tomcat Project missing

### ISSUE THREAD

**Issue by quiel77** [RedHatOfficial/RedHatOfficial.github.io#24]
Hi, 
Please add: 
Apache Tomcat who is the main component of JBoss Web Server
URL: https://tomcat.apache.org/
GIT: https://github.com/apache/tomcat

Thanks,
Ezequiel

**Comment by bproffitt** [comment]
Fixed with PR #66 . Closing, with thanks to @quiel77 and @erig0
