### ISSUE TITLE
Kubernetes is missing 

### ISSUE THREAD

**Issue by onyiny-ang** [RedHatOfficial/RedHatOfficial.github.io#25]
As the upstream to Openshift, many Red Hatters are actively involved in the Kubernetes project and special interest groups as part of their everyday work at Red Hat (myself included!).  
https://kubernetes.io/
https://github.com/kubernetes

**Comment by jzb** [comment]
We're actively involved in hundreds if not thousands of projects. I *think* that this is meant only for projects that we're the primary driver of. (Otherwise we're missing GNOME, the Linux kernel, GCC, and a slew of others.)

**Comment by onyiny-ang** [comment]
According to the README: https://github.com/RedHatOfficial/RedHatOfficial.github.io#criteria-for-adding-projects-to-the-page
Kubernetes qualifies as myself and many others are working on Kubernetes full time as part of our job at Red Hat.  
If you're judging by contributions, it's arguable who would be considered the _primary_ driver of Kubernetes: https://github.com/kubernetes/kubernetes/graphs/contributors
