### ISSUE TITLE
Update alphabetization to ignore "The"

### ISSUE THREAD

**Issue by castastrophe** [RedHatOfficial/RedHatOfficial.github.io#253]
Update how the list is alphabetized to ignore "The" at the beginning of a project

**Comment by Ayazzia01** [comment]
Hey this is my first time on github. What will I need to do exactly in this request?

**Comment by castastrophe** [comment]
I love your energy but if you haven't work in Angular, this is not a good task for you to pick up.  It would require going into the Angular app and writing regex to parse incoming strings for title to ignore `/the/ig`.  This is not my primary project so I don't have the hours at the moment to do a thorough hand-off.

**Comment by amruta-kashikar** [comment]
I want to work on this issue

**Comment by castastrophe** [comment]
Details are in the issue. Feel free to open a pull request and we'll take a look! Thanks!

**Comment by amruta-kashikar** [comment]
Here do we have to ignore 'The' for the project names which are added to the list of projects?
