### ISSUE TITLE
Uberfire is now AppFormer, and is inside KIE group

### ISSUE THREAD

**Issue by Christopher-Chianelli** [RedHatOfficial/RedHatOfficial.github.io#27]
Link to maintained repo: https://github.com/kiegroup/appformer

https://github.com/RedHatOfficial/RedHatOfficial.github.io/blob/10cefd7599e57252725d554acad7777b3926b757/app/data/projects.json#L178-L184

**Comment by bproffitt** [comment]
@Christopher-Chianelli So, should I just drop it in favor of KIE like I did initially with the other formerly separate projects?

**Comment by Christopher-Chianelli** [comment]
@bproffitt Depends on how granular you want the list to be. If you include AppFormer directly, then you should also include the rest of KIE group projects (AppFormer, Drools, OptaPlanner, etc.) as separate entries. If you do include it, it might be worth separating the data into two lists: Teams and Projects, and have Projects point to their team (so add a field, "team" to the Projects dataset whose value need to be exactly the same as the "teamName" of the corresponding team in the Teams dataset).

**Comment by bproffitt** [comment]
To be honest, I would like to just focus on the top-level projects, if we could. I don't want to start listing sub-projects if we can help it (like moVirt in oVirt-land). For consistency's sake, let's drop Uberfire until we can figure out a way to list sub-projects.

**Comment by Christopher-Chianelli** [comment]
@bproffitt Probably should add that to the README.md, so contributors know they should not add sub-projects.

**Comment by bproffitt** [comment]
Updated README and pulled UberFire out in #129 . Closing, with thanks!
