### ISSUE TITLE
Request to make linux-system-roles available in https://redhatofficial.github.io

### ISSUE THREAD

**Issue by nhosoi** [RedHatOfficial/RedHatOfficial.github.io#291]
## Description of the issue

Sorry, I mistakenly submit a pr https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/290 directly hoping to add a new project `linux-system-roles`. And the pr was already merged 6 days ago. But the project `linux-system-roles` does not appear in `https://redhatofficial.github.io/` yet.

Could you please tell me how to make `linux-system-roles` visible in `https://redhatofficial.github.io/? Thanks.

**Comment by bproffitt** [comment]
@zhawkins Can you advise? I merged this last week, and @nhosoi is correct, it's still not live on the site.

**Comment by zhawkins** [comment]
Taking a look @bproffitt 👀

**Comment by nhosoi** [comment]
Any progress on this issue?
BTW, thanks for taking care of this request.

**Comment by zhawkins** [comment]
@nhosoi this is resolved now. Check out https://redhatofficial.github.io and let me know what you think!

**Comment by nhosoi** [comment]
> @nhosoi this is resolved now. Check out https://redhatofficial.github.io and let me know what you think!

Excellent! Thank you soooo much for your help, @zhawkins.
