### ISSUE TITLE
Installing git

### ISSUE THREAD

**Issue by sundas56** [RedHatOfficial/RedHatOfficial.github.io#295]
Hello! Can anyone help me with installing git in Red Hat because when I try "yum install git", it shows this error
"This system is not registered with an entitlement server. You can use subscription-manager to register".
Then on registering through subscription-manager, I get this
"Unable to verify server's identity: certificate verify failed

**Comment by bproffitt** [comment]
This is not a support channel by any means. You might try Reddit /r/redhat, or contacting Red Hat support.
