### ISSUE TITLE
Site is no longer updating

### ISSUE THREAD

**Issue by bproffitt** [RedHatOfficial/RedHatOfficial.github.io#325]
## Description of the issue

The dev branch is not loading automatically into main, so site is not being updated.

### Steps to reproduce

The CI appears to be blocked by a network problem, as seen here https://github.com/RedHatOfficial/RedHatOfficial.github.io/runs/7658463790

One of my teammates looked into it, and believes the root cause is from this commit:

https://github.com/RedHatOfficial/RedHatOfficial.github.io/commit/e3df18983153b18c5d12c7ac539706fa6f58aabb

Which somehow has embedded a internal RH URL.

He does not know npm, and maybe that's a false lead, but he thinks it tries to download some deps, and can't get it from the nexus installation and fails.

But maybe it is broken before and the nexus DNS error is just a symptom and not the root cause.

More information, from him, when he tried to build it locally:

"The problem is that almost all dependencies are out of date, more or
less. So I relaxed the version number in package.json, remove the lock
file and hoped for the best.

"This showed that for some reason, we need the version 5.x of webpack.
Less than this, it conflits with a specific deps, more it conflict
with another dependency.

"Once I got that fixed, a issue with uglifyjs-webpack-plugin appeared.
So I removed it, and fixed the webpack buildconfig.

"The the syntax of one or two plugins changed, that I fixed as well.

"Now, it build, but the angular application do not work and show no
error anywhere. The bundle.js is loaded, etc. It just show nothing
anywhere.

"So if a webdev can take a look, that would help, because I am at the
limit of what I can do without involving a miracle :)"

### Expected behavior

The site should update, and it's not.

**Comment by mscherer** [comment]
So the teammate is me. As said, I am not a JS dev, but I think the main problem is deps are out of date (for example, nose-saas use node-gyp that do not work with python 3, as it try to detect python using a python snippet that only work on python 2). As the underlying OS is kept up to date, python 2 was removed.

I managed to get something built (using '*' everywhere), but upon testing angular fail to display components, which is not surprising since it moved from 1.8.0 to 14.x (or something like that).

**Comment by castastrophe** [comment]
I wanted to mention here that I used to be the developer on helping with this project but have since left the company.  The Netlify build is still running under my personal profile.  How would you like me to go about transferring this ownership?

**Comment by castastrophe** [comment]
cc @kylebuch8 or @bennypowers who might know who could assist with this in future?

**Comment by bennypowers** [comment]
Briefly scanning the build logs, it looks like there is an issue with the _private npm repository_ that is in use here at [https://repository.engineering.redhat.com](https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/v8flags/-/v8flags-2.1.1.tgz)

As for the netlify builds, If they are still needed, I'd recommend opening an open-source or paid account at netlify for this project

**Comment by mscherer** [comment]
Yeah, that's what I meant for "Which somehow has embedded a internal RH URL." but once that is solved (more or less), more issues appear.

**Comment by bennypowers** [comment]
@bproffitt would you be able to take a look at the [build failure](https://github.com/RedHatOfficial/RedHatOfficial.github.io/actions/runs/3090224345/jobs/4998749975) and give us an indication whether we're holding it wrong or not?

**Comment by bennypowers** [comment]
Ok I have a potential fix for this in a PR which updates from node-sass to dart sass. @bproffitt would you consider adding me with write perms so i don't have to fork?

PS. would you be interested in a PR which migrates from angular to lit+red-hat-design-system? such PR would drastically reduce both the code in this repo as well as the code over-the-wire to end user (thus improving loading performance)

**Comment by bproffitt** [comment]
@bennypowers Added. As for the build failure, @mscherer may be able to give you better data than I.
