### ISSUE TITLE
Some RedHatOfficial members are no longer at RH

### ISSUE THREAD

**Issue by alikins** [RedHatOfficial/RedHatOfficial.github.io#353]
### Steps to reproduce

1. Go to https://github.com/orgs/RedHatOfficial/people
2. See folks no longer at Red Hat (Ruth Suehle for example). I didn't check others.

### Expected behavior

RedHatOfficial would be for RH employees only. Though I could see why other folks could be still involved.

**Comment by bproffitt** [comment]
This is a non issue. Each project is open source to the general public by default. If a repo/project wants to close off access, they are welcome to. 

It's open source.
