### ISSUE TITLE
Red hat footer lacks proper UI design

### ISSUE THREAD

**Issue by Adityabandaru18** [RedHatOfficial/RedHatOfficial.github.io#366]
Improvements Needed for Red Hat Website Footer: Addressing Logo Size and Alignment Issues.
Checkout the issue while you scroll down the link:
https://www.redhat.com/en/about/our-community-contributions

Pictures for the relevance:
![Screenshot 2024-01-14 010632](https://github.com/RedHatOfficial/RedHatOfficial.github.io/assets/127210540/39507b3b-b9bc-4e82-bf32-4dfdd8c00cc3)
![Screenshot 2024-01-14 010640](https://github.com/RedHatOfficial/RedHatOfficial.github.io/assets/127210540/1c5c3eb4-07e2-4486-a4ca-a14b4852a7ec)

- (#100) Description

**Comment by bennypowers** [comment]
See http://ux.redhat.com/elements/footer

**Comment by Adityabandaru18** [comment]
@bennypowers that looks great!

**Comment by bennypowers** [comment]
Glad to hear it @Adityabandaru18. The Design System team is happy to advise on integrating the Red Hat Design System. Drop by our slack channel `#red-hat-design-system` if you have any questions

**Comment by Adityabandaru18** [comment]
@bennypowers  I'm excited to contribute to the Red Hat community and help resolve any bugs and issues. Could you please send me an invitation to join all the relevant channels in the Red Hat community? Here's my mail id : @adityabandaru70@gmail.com
