### ISSUE TITLE
Eclipse Che is missing

### ISSUE THREAD

**Issue by skabashnyuk** [RedHatOfficial/RedHatOfficial.github.io#4]
https://github.com/eclipse/che

**Comment by jzb** [comment]
Repeating a reply I posted about Kubernetes - Eclipse Che isn't a "Red Hat" project *per se* - we should distinguish between projects we started and drive (Fedora, oVirt, Ansible) vs. projects we are leaders in but aren't "ours" (GNOME, Kubernetes, Eclipse and Apache projects).

I'd suggest we make a distinction based on "do we hold or would we hold the trademark to this project if it was trademarked" to make the decision easy. Would we hold the trademark to Fedora? (We do.) Would we hold the trademark for Che? (No, Eclipse would.)
