### ISSUE TITLE
Please pick a license and add a LICENSE.md file. 

### ISSUE THREAD

**Issue by robynbergeron** [RedHatOfficial/RedHatOfficial.github.io#41]
SSIA.

**Comment by castastrophe** [comment]
Thanks!  We're working with legal to determine the appropriate license for publishing this type of content.  We didn't want to delay launch while we waited to hear back.

**Comment by bproffitt** [comment]
Update: Progress was made on this Friday afternoon. It is hoped a final choice will be made by early next week.

**Comment by castastrophe** [comment]
Address in PR: https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/116

**Comment by bproffitt** [comment]
PR #116 merged. Closing
