### ISSUE TITLE
Please explain what "Category" means

### ISSUE THREAD

**Issue by omajid** [RedHatOfficial/RedHatOfficial.github.io#42]
Is that the business unit that works on this project ("Middleware", "Operations", "Platform"), or the type of this project (used for "Development", "Documentation")?

Are multiple categories allowed?

**Comment by bproffitt** [comment]
Multiple categories are not allowed. I think for .NET Core specifically, it should be "Development"

**Comment by castastrophe** [comment]
As the PR in question was merged, I'm going to close this issue.
