### ISSUE TITLE
Style updates

### ISSUE THREAD

**Issue by starryeyez024** [RedHatOfficial/RedHatOfficial.github.io#45]
Suggested CSS improvements:

```
@media screen and (max-width:768px) {
  .table-header {
    display: none;
  }
  .table--component td {
    display:  block;
  }
  .table--component td:first-child {
    font-weight: bold;
  }
}
```

Add margin:0 to the .footer-copyright so it will vertically center. :)

**Comment by castastrophe** [comment]
Love this!  Thank you.  I'll work on getting these incorporated tonight or this weekend.

**Comment by castastrophe** [comment]
I have addressed this with the follow PR: https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/104
