### ISSUE TITLE
Duplicated information in README.md

### ISSUE THREAD

**Issue by robin-owen** [RedHatOfficial/RedHatOfficial.github.io#52]
The README.md file for this repository currently includes two paragraphs which contain the same information with slightly different wording  One has been placed directly below the top-level heading, the other directly before the "Adding a project" section.

**Comment by bproffitt** [comment]
Yeah... that's something to fix. Thanks!

**Comment by bproffitt** [comment]
Fixed. Thanks again! Closing.

**Comment by robin-owen** [comment]
Thank you! :+1:
