### ISSUE TITLE
Disambiguate the notion of "official Red Hat project" or "Red Hat project" vs "Projects Red Hat collaborates to" or "Projects Red Hat is involved in"

### ISSUE THREAD

**Issue by dmsimard** [RedHatOfficial/RedHatOfficial.github.io#56]
The wording in different places is a bit confusing as to the scope this tries to encompass.

For example:

[README.md](https://github.com/RedHatOfficial/RedHatOfficial.github.io/blob/27dc63f4ffec6736ce00ac0b2c69cd76d7e2ab99/README.md#red-hat-on-github)
> We’ve put together a comprehensive list of the projects in which Red Hat employees are actively involved.

Implies a list of projects that Red Hat *collaborates* to or is *involved* in.

We then follow up later with:

[README.md](https://github.com/RedHatOfficial/RedHatOfficial.github.io/blob/27dc63f4ffec6736ce00ac0b2c69cd76d7e2ab99/README.md#adding-a-project)
> Plus, as time goes by, more Red Hat projects will need to be added to this list.

And then there's the whole "RedHatOfficial" connotation or implication.

It's not for me to choose the purpose or the scope of this repository/project but the wording should be clear and consistent.
This way, contributors know what is appropriate (or not) to include here and manage people's expectations as to what is shown on the website.

**Comment by davidmalcolm** [comment]
Partly addressed by PR #48.

**Comment by davidmalcolm** [comment]
How about adding something like the following below the list on the main page:

"This is a list of projects hosted on GitHub in which Red Hat employees are actively involved.  An attempt at listing *all* such projects, not just on GitHub, can be seen at https://community.redhat.com/software/" 

or somesuch.

**Comment by kgaillot** [comment]
Agreed ... especially given Red Hat's large footprint in some upstream projects, being a good community member means avoiding any chance of being misconstrued as taking credit for or diminishing other people's work. I envision something like separate lists for "Communities led by Red Hat" and "Communities Red Hat is proud to collaborate with".

I also second the idea of clarifying "projects hosted or mirrored on Github", which is addressed by PR #48 and can be discussed there.

**Comment by dmsimard** [comment]
@fche @davidmalcolm We can't really deny there's a network effect at play here and we definitely have to pay attention around the implied dependency on GitHub and properly frame that.

Feel free to correct me if I'm wrong but I think the intent of this project is to ship something analogous to what [Microsoft](https://opensource.microsoft.com/) and [Google](https://opensource.google.com/projects/explore/featured) are doing... and guess what, those projects are on GitHub too.

**Comment by kgaillot** [comment]
> I'm at a loss as to why github-hosting should be a criterion for whether RH projects should get publicity here. Is this about endorsing github?

I'm pretty sure it's about having an official Github page for Red Hat.

E.g. the official Gitlab page for Red Hat (if one does or will exist) would list Gitlab-hosted projects that Red Hat is involved with, and so on. Red Hat's own community.redhat.com site, linked in this project's README, is where to go for a broader overview.

**Comment by bproffitt** [comment]
@kgaillot Is correct. It's a GitHub Page, so we're listing the GitHub hosted projects. But that does not preclude updating a primary list on community.redhat.com.

**Comment by fche** [comment]
> it's about having an official Github page for Red Hat.

Please forgive me, but I don't understand why we should construe that as limiting factor.  Does it benefit us somehow to avoid advertising other projects?

**Comment by bproffitt** [comment]
It does not. But this page is going to highlight GitHub projects. Other pages can highlight/advertise **all** the projects. I would like to get this one going, then put a call for action to get an overarching page started/updated somewhere. Perhaps on community.redhat.com/software

**Comment by fche** [comment]
OK.  Just a suggestion to clarify the intent further then: list the github.com repo URLs for the projects instead of their custom domains.  It takes quite a bit of clicking around to find e.g. where/how apache $foobar is actually co-hosted on github.

**Comment by kgaillot** [comment]
> Please forgive me, but I don't understand why we should construe that as limiting factor. Does it benefit us somehow to avoid advertising other projects?

Red Hat has numerous venues for advertising/promotion/publicity, including our own redhat.com websites. A Github page has a rather more constrained purpose, which is to indicate an organization's presence-on-Github. It makes sense, to me at least, that Red Hat's Github page would be a list of projects hosted or mirrored on Github to which Red Hat contributes. It's not Red Hat's "Internet home page", it's Red Hat's Github presence. This is in distinction to, say, Twitter, which is a general-purpose communication medium -- Github is a place for hosting particular projects.

Consider it this way: if we listed *all* projects that Red Hat contributes to on our Github page, we would be implicitly endorsing Github as the focal point of all open source.

I think our links back to community.redhat.com, and being explicit that these are "projects hosted or mirrored on Github", makes clear our wider contribution.

**Comment by bproffitt** [comment]
@fche That's a good idea, and will implement once the PRs settle down. Leaving this open to remind me.

**Comment by bproffitt** [comment]
This has been addressed in #120 Will also update public announcement on 3/26/18 to reflect these changes. Closing issue for now, always up for more feedback/suggestions.

**Comment by pabelanger** [comment]
FWIW: the way this now reads mean you should probably remobe all of the apache.org projects from projects.json. Since they are hosted at https://git-wip-us.apache.org/ not github.com.
