### ISSUE TITLE
please add TianoCore / edk2 / OVMF

### ISSUE THREAD

**Issue by lersek** [RedHatOfficial/RedHatOfficial.github.io#59]
* *projectName*: `TianoCore / edk2 / OVMF`
* *projectDescription*: cross-platform firmware development environment for the UEFI and Platform Initialization (PI) specifications; Red Hat is involved in firmware development for virtual machines
* *projectRepository*: https://github.com/tianocore/edk2
* *projectWebsite*: https://www.tianocore.org/
* *category*: Development

**Comment by bproffitt** [comment]
We are only adding things at the Project level, so it will need to be TitanoCore only. PR #107 takes care of this.
