### ISSUE TITLE
plz add smallfile

### ISSUE THREAD

**Issue by bengland2** [RedHatOfficial/RedHatOfficial.github.io#67]
```
{
  "projectName": "Smallfile",
  "projectDescription": "metadata-intensive workload generator for distributed POSIX filesystems",
  "projectRepository": "https://github.com/bengland2/smallfile",
  "category": "Storage"
}
```

This is used by members of perf & scale team, QE, and some partners and customers to performance-test Glusterfs, Cephfs, and NFS, and has even been used in a Windows cluster to test SMB.

I'll do a PR if I have to, but could someone drop it in for me?

**Comment by bengland2** [comment]
could you also add:

```
{
  "projectName": "fs-drift",
  "projectDescription": "stress and filesystem aging tool for distributed POSIX filesystems",
  "projectRepository": "https://github.com/parallel-fs-utils/fs-drift/commits/master",
  "category": "Storage"
}
```
I originally wrote this to test EMC Atmos distributed storage, and since then it has been used for Glusterfs cache tiering testing.   Lately it has been used by Samuel Petrovic of the Brno RHEL performance QE team, and he is the maintainer of late.

**Comment by bproffitt** [comment]
These will be added in PR #108. Waiting for Travis checks to be repaired, per issue #105

**Comment by bproffitt** [comment]
PR #108 successful, issue closed with thanks!
