### ISSUE TITLE
Search bar does not take into account project description

### ISSUE THREAD

**Issue by tarilabs** [RedHatOfficial/RedHatOfficial.github.io#8]
Case in point [project KIE](https://github.com/RedHatOfficial/RedHatOfficial.github.io/blob/10cefd7599e57252725d554acad7777b3926b757/app/data/projects.json#L390); people would likely search for keyword "Drools" or "optaplanner" or "jbpm" but currently the project description is not displayed (so it cannot be searched with the browser search functionality) nor the search bar does in fact operate on the project description despite not being shown.

**Comment by castastrophe** [comment]
That is a feature we would like to add but MVP for publishing this page quickly was searching by Project names.  I'd love to prioritize this functionality for future iterations of this page though.
