### ISSUE TITLE
Search results need to be fuzzier.

### ISSUE THREAD

**Issue by davidjpeacock** [RedHatOfficial/RedHatOfficial.github.io#80]
Searching for "OpenStack" or "openstack" does not bring up "redhat-openstack", meaning this (major) project doesn't appear to be listed unless people search for the very specific "redhat-openstack" string.

**Comment by castastrophe** [comment]
Thanks!  Yes, I'd love to update the search feature.  We threw it together quickly and just used a simple "startsWith".  We will make sure this gets prioritized.

**Comment by davidjpeacock** [comment]
Welcome!  This seems like a great endeavour; thank you and keep up the good work. :+1:

**Comment by davidjpeacock** [comment]
Hey - is this live on the prod site, or have you tested it in another place @castastrophe?

I just tried the live site and no dice.

:+1:

**Comment by castastrophe** [comment]
I tested locally and just merged the change so it will take a bit for
Travis to build.
