### ISSUE TITLE
Add redhatdemocentral

### ISSUE THREAD

**Issue by ishuverma** [RedHatOfficial/RedHatOfficial.github.io#82]
Please add redhatdemocentral, listing of various cross portfolio demos with red hat products

https://github.com/redhatdemocentral

**Comment by bproffitt** [comment]
These will be added in PR #109. Waiting for Travis checks to be repaired, per issue #105

**Comment by bproffitt** [comment]
PR #109 passed checks and merged. Closed, with thanks!
