### ISSUE TITLE
Reduce "Hero" size on front page

### ISSUE THREAD

**Issue by jzb** [RedHatOfficial/RedHatOfficial.github.io#89]
Viewing the site in Chrome on Linux the "hero" content on the front page (I think that's the proper terminology) where we've got "commit to collaborate" is far outsized. The projects themselves are "beneath the fold" so you don't even see the entire boxes for Ansible, Ceph, and ManageIQ. 

We should reduce that by about 2/3rds so the projects we're highlighting are immediately visible.

**Comment by castastrophe** [comment]
This was by design - that the cards would "peek" over the bottom of the page but not be fully visible - though your point is well made and I will pass this back through to the designers and get feedback on how to reduce the size further.

**Comment by castastrophe** [comment]
Looking at the code, the typography appears the right size but I think there's potentially too much padding on that top hero band.  @bproffitt Any opposition to my reducing the padding on the top band to this instead:

<img width="1482" alt="Screen Shot 2021-02-07 at 8 34 24 PM" src="https://user-images.githubusercontent.com/1840295/107166405-e5aec300-6983-11eb-9d9c-5e7b82fb99df.png">

Current: https://deploy-preview-234--red-hat.netlify.app

**Comment by bproffitt** [comment]
@castastrophe No opposition whatsoever! Thanks
